### ISSUE TITLE
It was working but then it stopped

### ISSUE THREAD

**Issue by decoder0007** [kgsensei/Quizizz-Bot-Flood#2]
I got 13 to join the first time I tried it but then it failed every time

**Comment by kgsensei** [comment]
Are you running the threaded copy or not?

**Comment by decoder0007** [comment]
> Are you running the threaded copy or not?

I was I tried both

**Comment by kgsensei** [comment]
Ok, The threaded copy isn't 100% finished yet so I would only use the other one. Another thing, recently Microsoft updated Edge and they made it so you need a new webdriver. You can get the latest one here: 'https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/' . All you need to do is replace the old webdriver exe with the new one. If that doesn't work run the nonThreaded file in the command line and send me the exact error.

**Comment by decoder0007** [comment]
I made a python program that opens the quizizz website and automatically
presses the tab button to get to the enter code box types the code and
presses enter then it presses tab some more times to get to the enter name
and types 10 random letters and presses enter then is does the same in a
new tab. It’s not as fast as I wanted it to be but I managed to get 100
working.

**Comment by kgsensei** [comment]
Ok, then.
